# Tweak the parse settings
CompileFlags:
  # Treat all files as C++, enable more warnings, use C++14
  Add: [-xc++, -Wall, -WExtra, -std=c++14]

  # Strip all other warning-related flags
  # Remove: [-W*]

  # Use clang++ as the compiler by replacing argv[0]
  Compiler: clang++

Diagnostics:
  # Recommend modern C++ alternatives
  Add: modernize*
