CompileFlags:                     # Tweak the parse settings
  Add: [-xc++, -Wall]             # treat all files as C++, enable more warnings
  # Remove: [-W*]                   # strip all other warning-related flags
  Compiler: clang++               # use clang++ as the compiler by replacing argv[0]

Diagnostics:
  Add: modernize*                 # recommend modern C++ alternatives
