# Tweak the parse settings
CompileFlags:
  # Treat all files as C++, enable more warnings, use C++17
  Add: [-std=c++17, -Wall, -WExtra, -xc++]

  # Strip all other warning-related flags
Remove: [-nologo*, -EHsc, -std:c++14*, -std:c++17*, -we4700*, -wd4996*, -we4172*, -Zm300*, -w34431*, -w34265*, -Zc:__cplusplus*, -w24928*, -MDd*, -w34906*, -Zi*, -Od*]

  # Use clang++ as the compiler by replacing argv[0]
  Compiler: clang++

Diagnostics:
  # Recommend modern C++ alternatives
  Add: modernize*
